spring.application.name=projeto-trio

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/atv_database
spring.datasource.username=root
spring.datasource.password=